#!/usr/bin/python3
import sys


def factorize(n):
    for i in range(2, n//2 + 1):
        if n % i == 0:
            return n // i, i
    return n, 1


def process_file(filename):
    try:
        with open(filename, 'r') as f:
            for line in f:
                n = int(line.strip())
                p, q = factorize(n)

                if p and q:
                    print("{}={}*{}".format(n, p, q))
                else:
                    print("No factors found for {}".format(n))
    except FileNotFoundError:
        print("Error: File {} not found".format(filename))
    except ValueError:
        print("Error: Ensure the file contains valid integers")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file = sys.argv[1]
    process_file(file)
