#!/usr/bin/python3
import sys


def factorize(n):
    for i in range(2, n//2 + 1):
        if n % i == 0:
            return n // i, i
    return n, 1


def process_file(filename):
    with open(filename, 'r') as f:
        for line in f:
            n = int(line.strip())
            p, q = factorize(n)
            print("{}={}*{}".format(n, p, q))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file = sys.argv[1]
    process_file(file)
